routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

// Route::post('login', 'LoginController@login');
// Route::get('/login', [App\Http\Controllers\Auth\LoginController::class, 'login'])->name('login');
// Route::get('/logout', [App\Http\Controllers\Auth\LoginController::class, 'logout'])->name('logout');
// Route::post('/logout', 'AuthController@logout');

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::group(['middleware' => 'auth'], function() {

Route::get('/items', [App\Http\Controllers\ItemController::class, 'index'])->name('items.index');

Route::get('/items/{item}', [App\Http\Controllers\ItemController::class, 'show'])->name('items.show');

Route::post('/bids-logs', [App\Http\Controllers\BidLogController::class, 'store'])->name('bid-logs.store');

Route::get('/bid-logs', [App\Http\Controllers\BidLogController::class, 'index'])->name('bid-logs.index');
Route::get('/bid-logs', [App\Http\Controllers\BidLogController::class, 'index'])->name('bid-logs.index');

// Route::get('/settings/{settings}', [App\Http\Controllers\SettingController::class, 'edit'])->name('settings.edit');

// Route::put('/settings/{settings}', [App\Http\Controllers\SettingController::class, 'update'])->name('settings.update');

Route::resource('/settings', App\Http\Controllers\SettingController::class)->only(['create', 'store']);
});


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::get('/home', 'App\Http\Controllers\HomeController@index')->name('home')->middleware('auth');

Route::group(['middleware' => 'auth'], function () {
	Route::get('table-list', function () {
		return view('pages.table_list');
	})->name('table');

	Route::get('typography', function () {
		return view('pages.typography');
	})->name('typography');

	Route::get('icons', function () {
		return view('pages.icons');
	})->name('icons');

	Route::get('map', function () {
		return view('pages.map');
	})->name('map');

	Route::get('notifications', function () {
		return view('pages.notifications');
	})->name('notifications');

	Route::get('rtl-support', function () {
		return view('pages.language');
	})->name('language');

	Route::get('upgrade', function () {
		return view('pages.upgrade');
	})->name('upgrade');
});

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'App\Http\Controllers\UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'App\Http\Controllers\ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'App\Http\Controllers\ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'App\Http\Controllers\ProfileController@password']);
});

app/Models/Setting.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    use HasFactory;

    protected $fillable = ['user_id', 'max_bid_amount'];


}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;

use App\Models\Setting;
use App\Http\Requests\Setting\UpdateRequest;
use Illuminate\Support\Facades\Auth;
use Exception;

use Illuminate\Http\Request;


class SettingController extends Controller
{



    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function create(Setting $setting)
    {
        // $model = $this->color->show($id);
        return view('settings.edit',compact('setting'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function store(UpdateRequest $request)
    {


        // dd($request);
        // try {


           $tt =  Setting::createOrUpdate(
            // ['user_id' =>Auth::user()->id],
            [
                'user_id'   => Auth::user()->id,
                'max_bid_amount'  => $request->get('max_bid_amount')
            ]);

            dd($tt);


        //     return redirect()->back()->with->with('success', 'Record created \ updated successfully');
        // } catch (Exception $e) {


        //     return redirect()->back()->with('error', $e->getMessage());

        // }

    }




}

resources/views/settings/edit.blade.php
@extends('layouts.app', ['activePage' => 'settings', 'titlePage' => __('Settings')])

@section('content')
  <div class="content">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">

          <form method="post" action="{{ route('settings.store') }}" autocomplete="off" class="form-horizontal">
            @csrf
            @method('post')

            <div class="card ">
              <div class="card-header card-header-primary">
                <h4 class="card-title">{{ __('Edit Settings') }}</h4>
                <p class="card-category">{{ __('Maximum bid Amount') }}</p>
              </div>


              <div class="card-body ">
                @if (session('status'))
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="alert alert-success">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                          <i class="material-icons">close</i>
                        </button>
                        <span>{{ session('status') }}</span>
                      </div>
                    </div>
                  </div>
                @endif

                <div class="row">
                  <label class="col-sm-2 col-form-label">{{ __('Maximum Bid Amount') }}</label>
                  <div class="col-sm-7">
                    <div class="form-group{{ $errors->has('max_bid_amount') ? ' has-danger' : '' }}">
                      <input class="form-control{{ $errors->has('max_bid_amount') ? ' is-invalid' : '' }}" name="max_bid_amount" id="input-name" type="text" placeholder="{{ __('Name') }}" value="" required="true" aria-required="true"/>
                      @if ($errors->has('max_bid_amount'))
                        <span id="name-error" class="error text-danger" for="input-name">{{ $errors->first('max_bid_amount') }}</span>
                      @endif
                    </div>
                  </div>
                </div>


              </div>
              <div class="card-footer ml-auto mr-auto">
                <button type="submit" class="btn btn-primary">{{ __('Save') }}</button>
              </div>
            </div>
          </form>
        </div>
      </div>



    </div>
  </div>
@endsection